version: '3'
networks:
  main:
services:
  traefik:
    image: 'traefik:v2.4'
    container_name: 'traefik'
    command:
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--entrypoints.http.address=:${HTTP_PORT}'
      - '--global.sendAnonymousUsage=false'
    ports:
      - '${HTTP_PORT}:${HTTP_PORT}'
      - '8080:8080'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
  api:
    container_name: '${API_URL}'
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./registry/api/${ENVIRONMENT}/Dockerfile
    volumes:
      - './:/opt/app-root/src:rw'
    ports:
      - ${HTTP_PORT}
    environment:
      PORT: ${HTTP_PORT}
      NODE_ENV: '${ENVIRONMENT}'
      APP_ENV: '${ENVIRONMENT}'
    command: '.s2i/bin/assemble'
    labels:
      traefik.enable: true
      traefik.http.routers.api-web.rule: Host(`${${API_URL}}`)
      traefik.http.routers.api-web.entrypoints: http
